# CONFIG FILE FOR RUINBOT

oper:
    nick: '<your oper nick (if exists)>'
    pass: '<your oper pass> (same here)'
    
twitter:
    consumersecret: '<insert here>'
    consumerkey: '<insert here>'
    accesstoken: '<insert here>'
    accesssecret: '<insert here>'

servers:
    tehsvk.net:
        port: 6667
        nick: RUINBot
        name: RUINBot
        channels:
            - '#RUINBot'
        auth:
            to: NickServ
            msg: 'identify <your pass>'

db:
    path: '/path/to/database'

cmdchar: '.' # Command character.
adminpwd: '<your admin password>'
ownernick: 'svkampen'