# CONFIG FILE FOR RUINBOT

oper:
    nick: '<your oper nick (if exists)>'
    pass: '<your oper pass> (same here)'
    
twitter:
    enabled: '<insert if enabled here>' # true or false.
    consumersecret: '<insert here if enabled>'
    consumerkey: '<insert here if enabled>'
    accesstoken: '<insert here if enabled>'
    accesssecret: '<insert here if enabled>'

servers:
    tehsvk.net:
        port: 6667
        nick: RUINBot
        name: RUINBot
        channels:
            - '#RUINBot'
        auth:
            to: NickServ
            msg: 'identify <your pass>'

db:
    path: '/path/to/database'

aboutowner:
    - 'Owner: blahblah'
    - 'Blah, blah blah'

cmdchar: '.' # Command character.
adminpwd: '<your admin password>'
ownernick: 'svkampen'